# Generated by Django 4.0 on 2024-07-18 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ea", models.PositiveSmallIntegerField(default=1)),
                ("price", models.PositiveIntegerField()),
                ("fee", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[("E", "판매완료"), ("B", "판매중")], max_length=1
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("renewal_date", models.DateTimeField(null=True)),
                ("sold_date", models.DateTimeField(null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="buy_user",
                        to="account.user",
                    ),
                ),
                (
                    "photo_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="product.photocard",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sale_user",
                        to="account.user",
                    ),
                ),
            ],
        ),
    ]
