# Generated by Django 4.2 on 2024-07-19 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0002_remove_salehistory_ea_alter_salehistory_photo_card_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salehistory",
            options={"ordering": ["id", "photo_card_id", "price", "renewal_date"]},
        ),
        migrations.AlterField(
            model_name="salehistory",
            name="price",
            field=models.PositiveIntegerField(
                help_text="1개당 가격",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="salehistory",
            name="renewal_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="salehistory",
            name="state",
            field=models.CharField(
                choices=[("E", "판매완료"), ("B", "판매중"), ("S", "등록")],
                default="S",
                max_length=1,
            ),
        ),
    ]
