# Generated by Django 4.2 on 2024-07-19 19:07

import django.core.validators
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0003_alter_salehistory_options_alter_salehistory_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salehistory",
            name="price",
            field=models.PositiveIntegerField(
                help_text="1개당 가격",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="salehistory",
            name="renewal_date",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
    ]
