# Generated by Django 4.0 on 2024-07-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_userwallet_and_more'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('fee', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('E', '판매완료'), ('B', '판매중')], max_length=1)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('renewal_date', models.DateTimeField(null=True)),
                ('sold_date', models.DateTimeField(null=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buy_user', to='account.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='register.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sale_user', to='account.user')),
            ],
        ),
    ]
