# Generated by Django 4.0 on 2024-07-16 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_photocard"),
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="product",
        ),
        migrations.AddField(
            model_name="sale",
            name="photo_card",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="register.photocard",
            ),
            preserve_default=False,
        ),
    ]
