# Generated by Django 4.0 on 2024-07-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.PositiveIntegerField(default=10000)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='account_use_created_f6d4bc_idx',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='created',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='updated',
            new_name='update_date',
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-create_date'], name='account_use_create__3108a1_idx'),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='account.user'),
        ),
    ]
