# Generated by Django 4.0 on 2024-07-17 12:20

import account.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_userwallet_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", account.managers.AccountManager()),
            ],
        ),
    ]
