# Generated by Django 4.0 on 2024-07-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_rename_cnt_photocard_ea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocard',
            name='ea',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
